/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MyRegistrationsRouteImport } from './routes/my-registrations'
import { Route as MyPaymentsRouteImport } from './routes/my-payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsRegistrationIdRouteImport } from './routes/payments.$registrationId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as DeveloperUsersRouteImport } from './routes/developer/users'
import { Route as DeveloperDashboardRouteImport } from './routes/developer/dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as DeveloperUsersUserIdRouteImport } from './routes/developer/users.$userId'
import { Route as AdminEventsCreateRouteImport } from './routes/admin/events.create'
import { Route as AdminEventsEventIdRegistrationsRouteImport } from './routes/admin/events.$eventId.registrations'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRegistrationsRoute = MyRegistrationsRouteImport.update({
  id: '/my-registrations',
  path: '/my-registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPaymentsRoute = MyPaymentsRouteImport.update({
  id: '/my-payments',
  path: '/my-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRegistrationIdRoute = PaymentsRegistrationIdRouteImport.update({
  id: '/payments/$registrationId',
  path: '/payments/$registrationId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const DeveloperUsersRoute = DeveloperUsersRouteImport.update({
  id: '/developer/users',
  path: '/developer/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperDashboardRoute = DeveloperDashboardRouteImport.update({
  id: '/developer/dashboard',
  path: '/developer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperUsersUserIdRoute = DeveloperUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => DeveloperUsersRoute,
} as any)
const AdminEventsCreateRoute = AdminEventsCreateRouteImport.update({
  id: '/admin/events/create',
  path: '/admin/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdRegistrationsRoute =
  AdminEventsEventIdRegistrationsRouteImport.update({
    id: '/admin/events/$eventId/registrations',
    path: '/admin/events/$eventId/registrations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-payments': typeof MyPaymentsRoute
  '/my-registrations': typeof MyRegistrationsRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/developer/dashboard': typeof DeveloperDashboardRoute
  '/developer/users': typeof DeveloperUsersRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/payments/$registrationId': typeof PaymentsRegistrationIdRoute
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/developer/users/$userId': typeof DeveloperUsersUserIdRoute
  '/admin/events/$eventId/registrations': typeof AdminEventsEventIdRegistrationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-payments': typeof MyPaymentsRoute
  '/my-registrations': typeof MyRegistrationsRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/developer/dashboard': typeof DeveloperDashboardRoute
  '/developer/users': typeof DeveloperUsersRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/payments/$registrationId': typeof PaymentsRegistrationIdRoute
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/developer/users/$userId': typeof DeveloperUsersUserIdRoute
  '/admin/events/$eventId/registrations': typeof AdminEventsEventIdRegistrationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-payments': typeof MyPaymentsRoute
  '/my-registrations': typeof MyRegistrationsRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/developer/dashboard': typeof DeveloperDashboardRoute
  '/developer/users': typeof DeveloperUsersRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/payments/$registrationId': typeof PaymentsRegistrationIdRoute
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/developer/users/$userId': typeof DeveloperUsersUserIdRoute
  '/admin/events/$eventId/registrations': typeof AdminEventsEventIdRegistrationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/login'
    | '/my-payments'
    | '/my-registrations'
    | '/register'
    | '/admin/dashboard'
    | '/developer/dashboard'
    | '/developer/users'
    | '/events/$eventId'
    | '/payments/$registrationId'
    | '/admin/events/create'
    | '/developer/users/$userId'
    | '/admin/events/$eventId/registrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/login'
    | '/my-payments'
    | '/my-registrations'
    | '/register'
    | '/admin/dashboard'
    | '/developer/dashboard'
    | '/developer/users'
    | '/events/$eventId'
    | '/payments/$registrationId'
    | '/admin/events/create'
    | '/developer/users/$userId'
    | '/admin/events/$eventId/registrations'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/login'
    | '/my-payments'
    | '/my-registrations'
    | '/register'
    | '/admin/dashboard'
    | '/developer/dashboard'
    | '/developer/users'
    | '/events/$eventId'
    | '/payments/$registrationId'
    | '/admin/events/create'
    | '/developer/users/$userId'
    | '/admin/events/$eventId/registrations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyPaymentsRoute: typeof MyPaymentsRoute
  MyRegistrationsRoute: typeof MyRegistrationsRoute
  RegisterRoute: typeof RegisterRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  DeveloperDashboardRoute: typeof DeveloperDashboardRoute
  DeveloperUsersRoute: typeof DeveloperUsersRouteWithChildren
  PaymentsRegistrationIdRoute: typeof PaymentsRegistrationIdRoute
  AdminEventsCreateRoute: typeof AdminEventsCreateRoute
  AdminEventsEventIdRegistrationsRoute: typeof AdminEventsEventIdRegistrationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-registrations': {
      id: '/my-registrations'
      path: '/my-registrations'
      fullPath: '/my-registrations'
      preLoaderRoute: typeof MyRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-payments': {
      id: '/my-payments'
      path: '/my-payments'
      fullPath: '/my-payments'
      preLoaderRoute: typeof MyPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$registrationId': {
      id: '/payments/$registrationId'
      path: '/payments/$registrationId'
      fullPath: '/payments/$registrationId'
      preLoaderRoute: typeof PaymentsRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/developer/users': {
      id: '/developer/users'
      path: '/developer/users'
      fullPath: '/developer/users'
      preLoaderRoute: typeof DeveloperUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/dashboard': {
      id: '/developer/dashboard'
      path: '/developer/dashboard'
      fullPath: '/developer/dashboard'
      preLoaderRoute: typeof DeveloperDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/users/$userId': {
      id: '/developer/users/$userId'
      path: '/$userId'
      fullPath: '/developer/users/$userId'
      preLoaderRoute: typeof DeveloperUsersUserIdRouteImport
      parentRoute: typeof DeveloperUsersRoute
    }
    '/admin/events/create': {
      id: '/admin/events/create'
      path: '/admin/events/create'
      fullPath: '/admin/events/create'
      preLoaderRoute: typeof AdminEventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/registrations': {
      id: '/admin/events/$eventId/registrations'
      path: '/admin/events/$eventId/registrations'
      fullPath: '/admin/events/$eventId/registrations'
      preLoaderRoute: typeof AdminEventsEventIdRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface DeveloperUsersRouteChildren {
  DeveloperUsersUserIdRoute: typeof DeveloperUsersUserIdRoute
}

const DeveloperUsersRouteChildren: DeveloperUsersRouteChildren = {
  DeveloperUsersUserIdRoute: DeveloperUsersUserIdRoute,
}

const DeveloperUsersRouteWithChildren = DeveloperUsersRoute._addFileChildren(
  DeveloperUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  MyPaymentsRoute: MyPaymentsRoute,
  MyRegistrationsRoute: MyRegistrationsRoute,
  RegisterRoute: RegisterRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  DeveloperDashboardRoute: DeveloperDashboardRoute,
  DeveloperUsersRoute: DeveloperUsersRouteWithChildren,
  PaymentsRegistrationIdRoute: PaymentsRegistrationIdRoute,
  AdminEventsCreateRoute: AdminEventsCreateRoute,
  AdminEventsEventIdRegistrationsRoute: AdminEventsEventIdRegistrationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
